In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 4, 5])

In [3]:
a

array([1, 2, 4, 5])

In [4]:
np.shape(a)

(4,)

In [5]:
np.eye(2,5),np.dtype(int)

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]]),
 dtype('int32'))

In [7]:
a.ravel()

array([1, 2, 4, 5])

In [8]:
a.ndim

1