# NumPy-
    - Numerical Python
    - it is a fundamental package
    - it is a python library used for working with arrays

### Features of Numpy-
    - Sequence order is preserved
    - indexing supported
    - slicing supported
    - homo./ hetro value accepted

In [1]:
# import numpy
import numpy

In [2]:
# make it simple: use module aliasing
import numpy as np

In [3]:
# check numpy version
np.__version__

'1.21.5'

In [4]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [6]:
a.ndim

1

In [7]:
b = np.array([[1,2,3], [4,5,6]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.ndim

2

In [10]:
c = np.array([[[1,2,3],[4,5,6]]])

In [11]:
c

array([[[1, 2, 3],
        [4, 5, 6]]])

In [12]:
c.ndim

3

In [13]:
c.shape

(1, 2, 3)

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [17]:
arr = np.arange(100000)

In [18]:
%time for i in range(100): arr = arr*3

CPU times: total: 0 ns
Wall time: 7.88 ms


In [19]:
ls = list(range(100000))

In [20]:
%time for j in range(100): [i*3 for i in ls]

CPU times: total: 500 ms
Wall time: 511 ms


In [21]:
arr.size

100000

In [22]:
c.size

6

In [23]:
c.itemsize

4

In [24]:
c.__sizeof__()

160

In [25]:
b.__sizeof__()

144

In [26]:
p = np.ones((3,4,3),dtype='int')

In [27]:
p

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [28]:
np.arange(100, 0, -1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [29]:
np.arange(1,101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [30]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [31]:
ar = np.array([[[1,2],[3,4]],[[6,7],[8,9]]])
ar

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [32]:
ar.ndim

3

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros((2,4),dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
np.arange(1,11,-1)

array([], dtype=int32)

In [36]:
n = np.array([[[10,20],[30,40]],[[50,60],[70,80]]]).ndim


In [37]:
n

3

In [38]:
np.array(['a',23,'j',9])

array(['a', '23', 'j', '9'], dtype='<U11')

In [39]:
n.shape

AttributeError: 'int' object has no attribute 'shape'

In [40]:
np.array([[[10,20],[30,40]],[[50,60],[70,80]]]).shape

(2, 2, 2)

In [41]:
np.array([[[10,20],[30,40]],[[50,60],[70,80]]]).ndim

3

In [42]:
ar = np.array([100,200,300])
ar

array([100, 200, 300])