In [1]:
import numpy as np

# np.array(object,dtype)

### Inspecting the properties of Numpy array

In [2]:
# 1D array
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 2D array
y = np.array([[12,3,5],[5,66,7],[1,0,69]])
y

array([[12,  3,  5],
       [ 5, 66,  7],
       [ 1,  0, 69]])

In [4]:
#check number of  elements
x.size

10

In [5]:
y.size

9

In [6]:
# gives total elements as array is 1D
len(x)

10

In [7]:
# give num of rows as array is 2D
len(y)

3

In [8]:
# if we want to check no. of rows and columns
x.shape

(10,)

In [9]:
y.shape

(3, 3)

# data type

In [10]:
x.dtype

dtype('int32')

In [11]:
y.dtype

dtype('int32')

In [12]:
# at the time of creation if i want to change dtype then
np.array([10,20],dtype='complex')

array([10.+0.j, 20.+0.j])

In [13]:
# but if after creation of an array i want to change dtype then???
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# change dtype of x
x.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
x.astype('float32')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [16]:
x.astype('f4')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [17]:
x.astype(np.float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## How to check all methods and properties supported by numpy

In [18]:
print(dir(x))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [19]:
# 'tobytes', 'tofile', 'tolist', 'tostring'
# when we want to covnert array in to anther type then use above options

In [20]:
y

array([[12,  3,  5],
       [ 5, 66,  7],
       [ 1,  0, 69]])

In [21]:
type(y)

numpy.ndarray

In [22]:
# convert into a list
y.tolist()

[[12, 3, 5], [5, 66, 7], [1, 0, 69]]

In [23]:
list(y)

[array([12,  3,  5]), array([ 5, 66,  7]), array([ 1,  0, 69])]

In [24]:
# can we create a dict from an array???
y 

array([[12,  3,  5],
       [ 5, 66,  7],
       [ 1,  0, 69]])

In [25]:
# convert into a bytes
y.tobytes()

b'\x0c\x00\x00\x00\x03\x00\x00\x00\x05\x00\x00\x00\x05\x00\x00\x00B\x00\x00\x00\x07\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00E\x00\x00\x00'

In [26]:
dict(y)

ValueError: dictionary update sequence element #0 has length 3; 2 is required

# Numpy operations: stat + math

In [27]:
y

array([[12,  3,  5],
       [ 5, 66,  7],
       [ 1,  0, 69]])

## np.sum()

In [28]:
# total addition
np.sum(y)

168

In [29]:
# rowwise addition
np.sum(y,axis= 1)

array([20, 78, 70])

In [30]:
# columnwise addition
np.sum(y,axis= 0)

array([18, 69, 81])

## np.mean()

In [31]:
y

array([[12,  3,  5],
       [ 5, 66,  7],
       [ 1,  0, 69]])

In [32]:
np.mean(y)

18.666666666666668

In [33]:
# rowwise mean
np.mean(y,axis= 1)

array([ 6.66666667, 26.        , 23.33333333])

In [34]:
# columnwise mean
np.mean(y,axis= 0)

array([ 6., 23., 27.])

## np.median()

In [35]:
y

array([[12,  3,  5],
       [ 5, 66,  7],
       [ 1,  0, 69]])

In [36]:
np.median(y)

5.0

In [37]:
# rowwise median
np.median(y,axis= 1)

array([5., 7., 1.])

In [38]:
# columnwise median
np.median(y,axis= 0)

array([5., 3., 7.])

## np.min()

In [39]:
np.min(y)

0

In [40]:
# rowwise min
np.min(y,axis= 1)

array([3, 5, 0])

In [41]:
# columnwise min
np.min(y,axis= 0)

array([1, 0, 5])

## np.max()

In [42]:
np.max(y)

69

In [43]:
# rowwise max
np.max(y,axis= 1)

array([12, 66, 69])

In [44]:
# columnwise max
np.max(y,axis= 0)

array([12, 66, 69])