In [1]:
import numpy as np

## Scalar mathematics

In [2]:
b = np.arange(24)

In [3]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [4]:
b.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

#### numpy array supports elementwise addition

In [5]:
b + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123])

In [6]:
np.add(b,100)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123])

In [ ]:
# + - * / % ** //

In [7]:
b % 5

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3], dtype=int32)

In [8]:
np.multiply(b,50)

array([   0,   50,  100,  150,  200,  250,  300,  350,  400,  450,  500,
        550,  600,  650,  700,  750,  800,  850,  900,  950, 1000, 1050,
       1100, 1150])

In [9]:
c = b.reshape(2,12)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [10]:
c / 5

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2],
       [2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6]])

In [11]:
c ** 2

array([[  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529]],
      dtype=int32)

In [12]:
np.divide(c,10)

array([[0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1],
       [1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3]])

## Vector math

In [13]:
x = np.array([[1,2],[2,3]])
y = np.array([[3,4]])

In [14]:
x

array([[1, 2],
       [2, 3]])

In [15]:
y

array([[3, 4]])

In [16]:
x + y

array([[4, 6],
       [5, 7]])

In [17]:
np.add(x,y)

array([[4, 6],
       [5, 7]])

In [18]:
x - y

array([[-2, -2],
       [-1, -1]])

In [19]:
np.subtract(x,y)

array([[-2, -2],
       [-1, -1]])

In [20]:
np.multiply(x,y)

array([[ 3,  8],
       [ 6, 12]])

In [21]:
np.divide(x,y)

array([[0.33333333, 0.5       ],
       [0.66666667, 0.75      ]])

In [22]:
np.power(x,y)

array([[ 1, 16],
       [ 8, 81]], dtype=int32)

In [23]:
x

array([[1, 2],
       [2, 3]])

In [24]:
y

array([[3, 4]])

In [25]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [27]:
x + c

ValueError: operands could not be broadcast together with shapes (2,2) (2,12) 

## Indexing over numpy array

In [28]:
b.resize(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
b.shape

(6, 4)

#### indexing works directly on row

In [30]:
b[0]

array([0, 1, 2, 3])

In [31]:
b[2]

array([ 8,  9, 10, 11])

In [32]:
b[-1]

array([20, 21, 22, 23])

In [33]:
b[-2]

array([16, 17, 18, 19])

#### if we want to access internal elements present in the row¶

In [34]:
b[0]

array([0, 1, 2, 3])

In [35]:
b[0,0]

0

In [36]:
b[0,-1]

3

In [37]:
b[0][-1]

3

In [38]:
id(b)

2506355432496

In [39]:
#lets try to change values from b
b[0,0]

0

In [40]:
b[0,0] = 100

In [41]:
b

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23]])

In [42]:
id(b)

2506355432496

### after changing data , id is not changing and changes persist in the same object¶

# hence numpy array is mutable in nature.....

## slicing

In [43]:
b

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23]])

In [44]:
b[:]   # default slicing works on rows

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23]])

In [45]:
b[2:]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
b[::-1]

array([[ 20,  21,  22,  23],
       [ 16,  17,  18,  19],
       [ 12,  13,  14,  15],
       [  8,   9,  10,  11],
       [  4,   5,   6,   7],
       [100,   1,   2,   3]])

In [47]:
b[-2:]

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
# fetch middle rows
# [ 8,  9, 10, 11],
# [12, 13, 14, 15]
b[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
"""
[100,  1,  2,  3]
[ 8,  9, 10, 11]
[16, 17, 18, 19]
"""
b[::2]

array([[100,   1,   2,   3],
       [  8,   9,  10,  11],
       [ 16,  17,  18,  19]])

In [50]:
"""
[100,  1,  2,  3]
[ 8,  9, 10, 11],
[12, 13, 14, 15],
"""
b[[0,2,3]]

array([[100,   1,   2,   3],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])