In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [3]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### add element in array

#### 1. append-
    - Signature: np.append(arr, values, axis=None)
    - Append values to the end of an array.

In [4]:
np.append(a,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
np.append(a,[12,13,14,15])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
# add 1 row
np.append(a,[[12,13,14]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [8]:
# add 1 column
np.append(a,[[12],[13],[14],[15]],axis=1)

array([[ 0,  1,  2, 12],
       [ 3,  4,  5, 13],
       [ 6,  7,  8, 14],
       [ 9, 10, 11, 15]])

#### 2. delete-
    - np.delete(arr, obj/index, axis=None)
    - Return a new array with sub-arrays along an axis deleted. For a one
    dimensional array, this returns those entries not returned by

In [9]:
np.delete(a,2)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
# delete row
np.delete(a,-1,axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
# delete column
np.delete(a,-1,axis=1)

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])

In [12]:
#delete column
np.delete(a,-2,axis=1)

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [13]:
np.delete(a,-3,axis=0)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### 3. Concatenate-

In [14]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
b = np.array([[0,0,0]])
b

array([[0, 0, 0]])

In [16]:
# concate a and b: along row operation performed
np.concatenate((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  0,  0]])

In [17]:
# columnwise concatenate
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
c = np.array([[0],[0],[0],[0]])
c

array([[0],
       [0],
       [0],
       [0]])

In [19]:
np.concatenate((a,c),axis=1)

array([[ 0,  1,  2,  0],
       [ 3,  4,  5,  0],
       [ 6,  7,  8,  0],
       [ 9, 10, 11,  0]])

## Till now axis= 0 means row 1and axis= 1 means column

#### 4. insert

In [20]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
np.insert(a,2,100)

array([  0,   1, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [22]:
np.insert(a,-1,-10)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, -10,  11])

In [23]:
# add a row between 3 n 6
np.insert(a,2,[-1,-2,-3],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [-1, -2, -3],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
# add a row between 3 n 6
np.insert(a,2,[[-1,-2,-3]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [-1, -2, -3],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
#  Add a new column before last column
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
np.insert(a,-1,[-1,-2,-3,-4],axis=1)

array([[ 0,  1, -1,  2],
       [ 3,  4, -2,  5],
       [ 6,  7, -3,  8],
       [ 9, 10, -4, 11]])

## Spliting of array

In [27]:
x = np.arange(24).reshape(6,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### split-
    - Split an array into multiple sub-arrays as views into `ary`.

In [28]:
np.split(x,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [29]:
np.split(x,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

#### vsplit-
    - Split an array into multiple sub-arrays vertically (row-wise)

In [30]:
np.vsplit(x,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

#### hsplit-
    - Split an array into multiple sub-arrays horizontally (column-wise)

In [31]:
np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [32]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
x1,y1 = np.vsplit(x,2)

In [34]:
x1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
y1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### np.where-
    - Return elements chosen from `x` or `y` depending on `condition`.
    - its condition based

In [36]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
np.where(x>10,1,0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [38]:
np.where(x>10,x,0)

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
gen = np.array(['Male','Female','Male','Female'])
gen

array(['Male', 'Female', 'Male', 'Female'], dtype='<U6')

In [40]:
# convert male to 0 and female to 1
np.where(gen == 'Male',0,1)
# when we have a column with binary(2) inputs
# and we need to convert as per the condition then use where

array([0, 1, 0, 1])

In [41]:
temp = [45,38,40,18,30,22,25,19]
# temp >30 set as High else low
np.where(np.array(temp)>30,'High','Low')

array(['High', 'High', 'High', 'Low', 'Low', 'Low', 'Low', 'Low'],
      dtype='<U4')