### Questions on NumPy Indexing

#### Que.1 Replace NumPy array elements that doesn’t satisfy the given condition

In [1]:
# 1D numpy array
import numpy as np
arr = np.array([75.42, 42.48, 60.32])
print('array is: \n', arr)
print('\nReplace all elements of array which are greater than 50. to 15.50')
arr[arr > 50.] = 15.50
print('new array is: \n', arr)

array is: 
 [75.42 42.48 60.32]

Replace all elements of array which are greater than 50. to 15.50
new array is: 
 [15.5  42.48 15.5 ]


In [2]:
# 2D numpy array
import numpy as np
arr = np.array([[75, 42, 60],
              [5, 50, 25]])
print('array is: \n', arr)
print('\nReplace all elements of array which are greater than 40 to 15')
arr[arr > 40] = 15
print('new array is: \n', arr)

array is: 
 [[75 42 60]
 [ 5 50 25]]

Replace all elements of array which are greater than 40 to 15
new array is: 
 [[15 15 15]
 [ 5 15 25]]


In [3]:
# 3D numpy array
import numpy as np
arr = np.array([[[5, 42, 0], [12,5,8]],
              [[2,5,13], [5, 50, 5]],
              [[5,16,8], [12,5,9]]])
print('array is: \n', arr)
print('\nReplace all elements of array which are less than 10 to 0')
arr[arr < 10] = 0
print('new array is: \n', arr)

array is: 
 [[[ 5 42  0]
  [12  5  8]]

 [[ 2  5 13]
  [ 5 50  5]]

 [[ 5 16  8]
  [12  5  9]]]

Replace all elements of array which are less than 10 to 0
new array is: 
 [[[ 0 42  0]
  [12  0  0]]

 [[ 0  0 13]
  [ 0 50  0]]

 [[ 0 16  0]
  [12  0  0]]]


#### Que.2 Return the indices of elements where the given condition is satisfied

In [4]:
import numpy as np
np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]], [[5, 6], [7, 8]])

array([[1, 6],
       [3, 4]])

In [5]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print('array is: \n', a) 
print('\nIndices of elements < 4:')  
b = np.where(a<4)
print(b) 
print('\nElements which are < 4: \n', a[b])

array is: 
 [[1 2 3]
 [4 5 6]]

Indices of elements < 4:
(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))

Elements which are < 4: 
 [1 2 3]


#### Que.3 How to get values of an NumPy array at certain index positions?

In [6]:
import numpy as np
a1 = np.array([11, 10, 22, 30, 33])
print('Array 1:', a1)
a2 = np.array([1, 15, 60])
print('\nArray 2:', a2)
print('\nTake 1 and 15 from Array 2 and put them in 1st and 5th position of Array 1')
a1.put([0, 4], a2) 
print('\nResultant Array:', a1)

Array 1: [11 10 22 30 33]

Array 2: [ 1 15 60]

Take 1 and 15 from Array 2 and put them in 1st and 5th position of Array 1

Resultant Array: [ 1 10 22 30 15]


#### Que.4 Replace negative value with zero in numpy array

In [7]:
import numpy as np
ar1 = np.array([1, 2, -3, 4, -5, -6])
print('initial array:', ar1)
ar1[ar1 < 0] = 0
print('New resulting array: ', ar1)

initial array: [ 1  2 -3  4 -5 -6]
New resulting array:  [1 2 0 4 0 0]


#### Que.5 Find indices of elements equal to zero in a NumPy array

In [8]:
import numpy as np
arr = np.array([1, 0, 2, 0, 3, 0, 0, 5,
                    6, 7, 5, 0, 8])
print('Original array: \n',arr)
res = np.where(arr == 0)[0]
print('\nIndices of elements equal to zero:', res)

Original array: 
 [1 0 2 0 3 0 0 5 6 7 5 0 8]

Indices of elements equal to zero: [ 1  3  5  6 11]


In [9]:
import numpy as np
arr = np.array([[0, 2, 3],
                [4, 1, 0],
                [0, 0, 2]])
print('Original array: \n', arr)
res = np.argwhere(arr == 0)
print('\nIndices of null elements:\n', res)

Original array: 
 [[0 2 3]
 [4 1 0]
 [0 0 2]]

Indices of null elements:
 [[0 0]
 [1 2]
 [2 0]
 [2 1]]


In [10]:
import numpy as np
arr = np.array([1, 0, 2, 0, 3, 0, 0, 5,
                    6, 7, 5, 0, 8])
print('Original array: \n',arr)
res = np.nonzero(arr == 0)
print('\nIndices of elements equal to zero: \n', res)

Original array: 
 [1 0 2 0 3 0 0 5 6 7 5 0 8]

Indices of elements equal to zero: 
 (array([ 1,  3,  5,  6, 11], dtype=int64),)


#### Que.6 How to Remove columns in Numpy array that contains non-numeric values?

In [12]:
import numpy as np
arr = np.array([[10.5, 22.5, np.nan],
                  [41, 52.5, np.nan]])
  
print('Given array: \n', arr)
print('\nRemove all columns containing non-numeric elements:')
print(arr[:, ~np.isnan(arr).any(axis=0)])

Given array: 
 [[10.5 22.5  nan]
 [41.  52.5  nan]]

Remove all columns containing non-numeric elements:
[[10.5 22.5]
 [41.  52.5]]


#### Que.7 How to access different rows of a multidimensional NumPy array?

In [13]:
import numpy as np
arr = np.array([[10, 20, 30], 
                [40, 5, 66], 
                [70, 88, 94]])
print('Given Array: \n', arr)
res = arr[[0,2]]
print('\nAccessed Rows: \n', res)

Given Array: 
 [[10 20 30]
 [40  5 66]
 [70 88 94]]

Accessed Rows: 
 [[10 20 30]
 [70 88 94]]


#### Que.8 Get row numbers of NumPy array having element larger than X

In [14]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5],
                  [10, -3, 30, 4, 5],
                  [3, 2, 5, -4, 5],
                  [9, 7, 3, 6, 5]])
X = 6
print('Given Array: \n', arr)
out = np.where(np.any(arr > X, axis = 1))
print('\nResult: \n', out)

Given Array: 
 [[ 1  2  3  4  5]
 [10 -3 30  4  5]
 [ 3  2  5 -4  5]
 [ 9  7  3  6  5]]

Result: 
 (array([1, 3], dtype=int64),)


#### Que.9 Get filled the diagonals of NumPy array

In [15]:
import numpy as np
arr = np.array([[1, 2], [2, 1]])
np.fill_diagonal(arr, 5)  
print('diagonal of array is: \n', arr)

diagonal of array is: 
 [[5 2]
 [2 5]]


In [16]:
import numpy as np
arr = np.zeros((3, 3), int)
np.fill_diagonal(arr, 1)
print('diagonal of array is: \n', arr)

diagonal of array is: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


#### Que.10 Check elements present in the NumPy array

In [17]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5])
lis = [1, 3, 5]
a = np.isin(a1, lis) 
print('elements present in array: \n', a)

elements present in array: 
 [ True False  True False  True]


In [18]:
import numpy as np
a1 = np.array([[1, 3], [5, 7], [9, 11]])
lis = [1, 3, 11, 9]
a = np.isin(a1, lis) 
print('elements present in array: \n', a)

elements present in array: 
 [[ True  True]
 [False False]
 [ True  True]]


#### Que.11 Combined array index by index

In [19]:
import numpy as np
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print('Combined array: \n', np.dstack((a1, a2)))

Combined array: 
 [[[1 4]
  [2 5]
  [3 6]]]


In [20]:
import numpy as np
a1 = np.array([[10], [2], [13]])
a2 = np.array([[41], [55], [6]])
print('Combined array: \n', np.dstack((a1, a2)))

Combined array: 
 [[[10 41]]

 [[ 2 55]]

 [[13  6]]]
