### Questions on NumPy Array


#### Que.1 How to create an empty and a full NumPy array?

In [1]:
import numpy as np
emp = np.empty((3,4), dtype='int8')
print('empty array:')
print(emp)

ful = np.full([3,3], 'shiv')
print('\nfull array:')
print(ful)

empty array:
[[115   0  92   0]
 [ 99   0 104   0]
 [ 97   0 118   0]]

full array:
[['shiv' 'shiv' 'shiv']
 ['shiv' 'shiv' 'shiv']
 ['shiv' 'shiv' 'shiv']]


#### Que.2 Create a Numpy array filled with all zeros

In [2]:
import numpy as np
a = np.zeros(5, dtype='int8')
print('matrix of a:', a)

b = np.zeros((5, 4), dtype='int8')
print('\nmatrix of b: \n', b)

c = np.zeros((5, 4))
print('\nmatrix of c: \n', c)

d = np.zeros((2, 3), dtype=float)
print('\nmatrix of d: \n', d)

matrix of a: [0 0 0 0 0]

matrix of b: 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

matrix of c: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

matrix of d: 
 [[0. 0. 0.]
 [0. 0. 0.]]


#### Que.3 Create a Numpy array filled with all ones

In [3]:
import numpy as np
a = np.ones(5, dtype='int8')
print('matrix of a:', a)

b = np.ones((5, 4), dtype='int8')
print('\nmatrix of b: \n', b)

c = np.ones((5, 4))
print('\nmatrix of c: \n', c)

d = np.ones((2, 3), dtype=float)
print('\nmatrix of d: \n', d)

matrix of a: [1 1 1 1 1]

matrix of b: 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

matrix of c: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

matrix of d: 
 [[1. 1. 1.]
 [1. 1. 1.]]


#### Que.4 Check whether a Numpy array contains a specified row

In [4]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]])
  
print('array is: \n', arr)
print('\ncheck for some lists are:')
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())

array is: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

check for some lists are:
True
False
False
True


#### Que.5 How to Remove rows in Numpy array that contains non-numeric values?

In [5]:
# 2x3 Numpy array
import numpy as np
arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
print('array is: \n', arr)  
print('\nRemove all rows containing non-numeric elements')
print(arr[~np.isnan(arr).any(axis=1)])

array is: 
 [[10.5 22.5  3.8]
 [41.   nan  nan]]

Remove all rows containing non-numeric elements
[[10.5 22.5  3.8]]


In [6]:
import numpy as np
arr = np.array([[10.5, 22.5, 3.8],
                 [23.45, 50, 78.7],
                 [41, np.nan, np.nan]])
print('array is: \n', arr)  
print('\nRemove all rows containing non-numeric elements')
print(arr[~np.isnan(arr).any(axis=1)])

array is: 
 [[10.5  22.5   3.8 ]
 [23.45 50.   78.7 ]
 [41.     nan   nan]]

Remove all rows containing non-numeric elements
[[10.5  22.5   3.8 ]
 [23.45 50.   78.7 ]]


#### Que.6 Remove single-dimensional entries from the shape of an array

In [7]:
import numpy as np
arr = np.array([[[2, 2, 2], [2, 2, 2]]])   
print ('Input array: \n', arr) 
print('\nShape of input array:', arr.shape)    
arr1 = np.squeeze(arr)   
print ('\nOutput squeezed array: \n', arr1)
print('\nShape of output array:', arr1.shape) 

Input array: 
 [[[2 2 2]
  [2 2 2]]]

Shape of input array: (1, 2, 3)

Output squeezed array: 
 [[2 2 2]
 [2 2 2]]

Shape of output array: (2, 3)


In [8]:
import numpy as np
arr = np.arange(9).reshape(1,3,3)   
print ('Input array: \n', arr) 
print('\nShape of input array:', arr.shape) 
arr1 = np.squeeze(arr, axis=0)   
print ('\nOutput squeezed array: \n', arr1)
print('\nShape of output array:', arr1.shape) 

Input array: 
 [[[0 1 2]
  [3 4 5]
  [6 7 8]]]

Shape of input array: (1, 3, 3)

Output squeezed array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Shape of output array: (3, 3)


#### Que.7 Find the number of occurrences of a sequence

In [9]:
import numpy
arr = numpy.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])
print ('Input array: \n', arr)
out = repr(arr).count('9, 4')
print ('\nNumber of occurence is:', out) 

Input array: 
 [[2 8 9 4]
 [9 4 9 4]
 [4 5 9 7]
 [2 9 4 3]]

Number of occurence is: 4


#### Que.8 Find the most frequent value

In [10]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
print('Original array: \n', x)
y = np.bincount(x).argmax()
print('\nMost frequent value in the above array:', y)

Original array: 
 [1 2 3 4 5 1 2 1 1 1]

Most frequent value in the above array: 1


In [11]:
import numpy as np  
x = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print('Original array: \n', x)
print('\nMost frequent value in above array')
y = np.bincount(x)
maximum = max(y)
for i in range(len(y)):
    if y[i] == maximum:
        print(i, end=', ')

Original array: 
 [1 1 1 2 3 4 2 4 3 3]

Most frequent value in above array
1, 3, 

#### Que.9 Combining a one and a two-dimensional NumPy Array

In [12]:
import numpy as np
arr_1d = np.arange(5)
print('One dimensional array:', arr_1d)
arr_2d = np.arange(10).reshape(2,5)
print('\nTwo dimensional array: \n', arr_2d)
for a, b in np.nditer([arr_1d, arr_2d]):
    print('\n%d:%d' % (a, b))

One dimensional array: [0 1 2 3 4]

Two dimensional array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

0:0

1:1

2:2

3:3

4:4

0:5

1:6

2:7

3:8

4:9


#### Que.10 How to build an array of all combinations of two NumPy arrays?

In [13]:
import numpy as np
arr_1 = np.array([1, 2])
arr_2 = np.array([4, 6])
print('Array 1:', arr_1)  
print('\nArray 2:', arr_2)
comb_array = np.array(np.meshgrid(arr_1, arr_2)).T.reshape(-1, 2)
print('\nCombine element array: \n', comb_array)

Array 1: [1 2]

Array 2: [4 6]

Combine element array: 
 [[1 4]
 [1 6]
 [2 4]
 [2 6]]


#### Que.11 How to add a border around a NumPy array?

In [14]:
import numpy as np
a = np.ones((2, 2))  
print('Original array: \n', a)
print('\n0 on the border and 1 inside the array')
a = np.pad(a, pad_width=1, mode='constant',
               constant_values=0)
  
print(a)

Original array: 
 [[1. 1.]
 [1. 1.]]

0 on the border and 1 inside the array
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


#### Que.12 How to compare two NumPy arrays?

In [15]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [3, 4]])
c = a == b
d = c.all() 
print('compare two array is', d)

compare two array is True


In [16]:
import numpy as np
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[1, 2], [3, 4]])
if np.array_equal(a1, a2):
    print('Two array are Equal')
else:
    print('Two array are Not Equal')

Two array are Equal


#### Que.13 How to check whether specified values are present in NumPy array?

In [17]:
import numpy as np
a = np.array([[2, 3, 0],
             [4, 1, 6]])
print('Given array: \n', a)
print(2 in a)
print(0 in a)
print(50 in a)
print(10 in a)

Given array: 
 [[2 3 0]
 [4 1 6]]
True
True
False
False


#### Que.14 How to get all 2D diagonals of a 3D NumPy array?

In [18]:
import numpy as np
arr = np.arange(3 * 2 * 2).reshape(3, 2, 2)
print('Original 3d array: \n', arr)  
diag_arr = np.diagonal(arr, axis1 = 1,
                       axis2 = 2)
print('2d diagonal array: \n', diag_arr)

Original 3d array: 
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
2d diagonal array: 
 [[ 0  3]
 [ 4  7]
 [ 8 11]]


#### Que.15 Flatten a Matrix

In [19]:
import numpy as np
a = np.array([[2, 3], [4, 5]])
f = a.flatten()
print('flatten a matrix:', f)

flatten a matrix: [2 3 4 5]


In [20]:
import numpy as np
a = np.array([[6, 9, 12], [8, 5, 2], [18, 21, 24]])
f = a.flatten(order='A')
print('flatten a matrix: \n', f)

flatten a matrix: 
 [ 6  9 12  8  5  2 18 21 24]


#### Que.16 Flatten a 2d numpy array into 1d array

In [21]:
import numpy as np
arr = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print('initial array:  \n', arr)
res = arr.flatten()
print('\nNew resulting array: \n', res)

initial array:  
 [[1 2 3]
 [2 4 5]
 [1 2 3]]

New resulting array: 
 [1 2 3 2 4 5 1 2 3]


In [22]:
import numpy as np
arr = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print('initial array:  \n', arr)
res = arr.ravel()
print('\nNew resulting array: \n', res)

initial array:  
 [[1 2 3]
 [2 4 5]
 [1 2 3]]

New resulting array: 
 [1 2 3 2 4 5 1 2 3]


In [23]:
import numpy as np
arr = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print('initial array:  \n', arr)
res = arr.reshape(1, 9)
print('\nNew resulting array: \n', res)

initial array:  
 [[1 2 3]
 [2 4 5]
 [1 2 3]]

New resulting array: 
 [[1 2 3 2 4 5 1 2 3]]


#### Que.17 Move axes of an array to new positions

In [24]:
import numpy as np 
arr = np.zeros((1, 2, 3, 4))
res = np.moveaxis(arr, 0, -1).shape 
print('array to new positions:', res)

array to new positions: (2, 3, 4, 1)


In [25]:
import numpy as np 
arr = np.zeros((1, 2, 3, 4))
res = np.moveaxis(arr, -1, 0).shape 
print('array to new positions:', res)

array to new positions: (4, 1, 2, 3)


#### Que.18 Interchange two axes of an array

In [26]:
import numpy as np 
arr = np.array([[2, 3, 4]])
res = np.swapaxes(arr, 0, 1) 
print('array interchange two axes: \n', res)

array interchange two axes: 
 [[2]
 [3]
 [4]]


In [27]:
import numpy as np 
arr = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
res = np.swapaxes(arr, 0, 2) 
print('array interchange two axes: \n', res)

array interchange two axes: 
 [[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


#### Que.19 Counts the number of non-zero values in the array

In [28]:
import numpy as np 
arr = [[0, 1, 2, 3, 0], [0, 5, 6, 0, 7]]
res = np.count_nonzero(arr)  
print('Count of non-zero values:', res) 

Count of non-zero values: 6


In [29]:
import numpy as np 
arr = [[0, 1, 2, 3, 0], [0, 5, 6, 0, 7]]
res = np.count_nonzero(arr, axis=1)  
print('Count of non-zero values:', res) 

Count of non-zero values: [3 3]


#### Que.20 Count the number of elements along a given axis

In [30]:
import numpy as np 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print('No. of element is:', np.size(arr))

No. of element is: 8


In [31]:
import numpy as np 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print('No. of element axis 0:', np.size(arr, 0))
print('No. of element axis 1:', np.size(arr, 1))

No. of element axis 0: 2
No. of element axis 1: 4


#### Que.21 Change data type of given numpy array

In [32]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print('array is:', arr)
print('\narray data type is:', arr.dtype)
arr = arr.astype('float64')
print('\nChanging array is: \n', arr)
print('\nChanging array data type is:', arr.dtype)

array is: [10 20 30 40 50]

array data type is: int32

Changing array is: 
 [10. 20. 30. 40. 50.]

Changing array data type is: float64


In [33]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print('array is:', arr)
print('\narray data type is:', arr.dtype)
arr = arr.astype('complex64')
print('\nChanging array is: \n', arr)
print('\nChanging array data type is:', arr.dtype)

array is: [10 20 30 40 50]

array data type is: int32

Changing array is: 
 [10.+0.j 20.+0.j 30.+0.j 40.+0.j 50.+0.j]

Changing array data type is: complex64


#### Que.22 Reverse a numpy array

In [34]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
res = np.flip(arr)
print('reverse array:', res)

reverse array: [5 4 6 3 2 1]


In [35]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
res = arr[::-1]
print('reverse array:', res)

reverse array: [5 4 6 3 2 1]


In [36]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
res = np.flipud(arr)
print('reverse array:', res)

reverse array: [5 4 6 3 2 1]


#### Que.23 How to make a NumPy array read-only?

In [37]:
import numpy as np 
a = np.zeros(11)
print('Before any change: \n', a) 
a[1] = 2
print('\nBefore after first change: \n', a)
a.setflags(write=False)
print('\nAfter making array immutable on attempting  second change:')
a[1] = 7

Before any change: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Before after first change: 
 [0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

After making array immutable on attempting  second change:


ValueError: assignment destination is read-only

#### Que.24. Trim the leading and/or trailing zeros from a 1-D array

In [38]:
import numpy as np 
arr = np.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0))
res = np.trim_zeros(arr)
print('array is:', res)

array is: [ 1  5  7  0  6  2  9  0 10]


In [39]:
import numpy as np 
arr = np.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0))
res = np.trim_zeros(arr, 'f')
print('array is:', res)

array is: [ 1  5  7  0  6  2  9  0 10  0  0]


In [40]:
import numpy as np 
arr = np.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0))
res = np.trim_zeros(arr, 'b')
print('array is:', res)

array is: [ 0  0  0  0  1  5  7  0  6  2  9  0 10]
